server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:Eisoo.com123@tcp(192.168.0.105:3306)/ReviewServiceDB?parseTime=True&loc=Local
  redis:
    addr: 192.168.0.105:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
