# 第三代语法
version: '3'                                                   # 指定使用docker-compose第3版本的语法

# 自定义数据卷(服务数据持久化)，位于宿主机/var/lib/docker/volumes内
volumes:                                                       # 定义持久化存储卷
  databasedata:                                                # MySQL数据存储卷，用于持久化数据库数据
  databaseconf:                                                # MySQL配置存储卷，用于持久化数据库配置
  etcddata:                                                    # 添加etcd数据卷
  natsdata:                                                     # 添加 NATS 数据卷
  consuldata:                                                   # 添加 Consul 数据卷
  kafkadata:                                                   # 添加 Kafka 数据卷
  zookeeperdata:                                               # 添加 Zookeeper 数据卷
  kafkamanagerdata:                                            # 添加 kafkamanagerdata 数据卷

services:                                                      # 定义服务列表
  codemysql:                                                   # MySQL服务配置
    build:                                                     # 构建配置
      context: .                                               # 构建上下文为当前目录
      dockerfile: compose/mysql/Dockerfile                      # 使用的Dockerfile路径
    image: kratos_mysql                                        # 构建后的镜像名称
    container_name: kratos_mysql                               # 容器名称
    restart: always                                            # 容器总是自动重启
    volumes:                                                   # 卷挂载配置
      # 数据挂载
      - databasedata:/var/lib/mysql/                           # 将数据卷挂载到容器的数据目录
      # 配置挂载
      - databaseconf:/etc/mysql/conf.d/                        # 将配置卷挂载到容器的配置目录
    #env_file:                                                 # 环境变量文件（已注释）
    #  - ./.envs/.production/.my
    # 设置数据库密码、创建一个数据库
    environment:                                               # 环境变量配置
      # root 密码
      - "MYSQL_ROOT_PASSWORD=Eisoo.com123"                     # 设置MySQL root用户密码
    command: --init-file /docker-entrypoint-initdb.d/init.sql  # 启动命令，指定初始化SQL文件
    ports:                                                     # 端口映射
      - "3306:3306"                                           # 将容器的3306端口映射到主机的3306端口

  codenginx:                                                   # Nginx服务配置
    build:                                                     # 构建配置
      context: .                                               # 构建上下文为当前目录
      dockerfile: compose/nginx/Dockerfile                      # 使用的Dockerfile路径
    image: kratos_nginx                                        # 构建后的镜像名称
    container_name: kratos_nginx                               # 容器名称
    restart: always                                            # 容器总是自动重启
    # 暴露全端口
    network_mode: host                                         # 使用主机网络模式，直接使用宿主机的网络

  codeetcd:                                                    # etcd服务配置
    build:
      context: .
      dockerfile: compose/etcd/Dockerfile
    image: kratos_etcd
    container_name: kratos_etcd
    restart: always
    volumes:
      - etcddata:/bitnami/etcd                                # 数据持久化
    ports:
      - "2379:2379"                                           # 客户端通信端口
      - "2380:2380"                                           # 集群通信端口
    environment:
      - ETCD_INITIAL_CLUSTER_STATE=new                        # 初始集群状态
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1            # 集群token

  codenats:                                                     # NATS 服务配置
    build:
      context: .
      dockerfile: compose/nats/Dockerfile
    image: kratos_nats
    container_name: kratos_nats
    restart: always
    volumes:
      - natsdata:/data                                         # 数据持久化
      - ./compose/nats/nats-server.conf:/etc/nats/nats-server.conf:ro  # 配置文件挂载
    ports:
      - "4222:4222"                                            # 客户端连接端口
      - "8222:8222"                                            # HTTP 管理端口
      - "6222:6222"                                            # 集群通信端口
    ulimits:                                                   # 系统资源限制
      nofile:
        soft: 65536
        hard: 65536

  codeconsul:                                                   # Consul 服务配置
    build:
      context: .
      dockerfile: compose/consul/Dockerfile
    image: kratos_consul
    container_name: kratos_consul
    restart: always
    volumes:
      - consuldata:/consul/data                                # 数据持久化
      - ./compose/consul/config.json:/consul/config/config.json:ro  # 配置文件挂载
    ports:
      - "8500:8500"                                           # HTTP API & UI
      - "8600:8600/tcp"                                       # DNS
      - "8600:8600/udp"                                       # DNS
      - "8300:8300"                                           # Server RPC
      - "8301:8301"                                           # Serf LAN
      - "8302:8302"                                           # Serf WAN
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=true                    # 允许绑定特权端口
    cap_add:
      - NET_ADMIN                                             # 允许网络管理权限
      - SYS_TIME                                              # 允许时间同步

  codekafka:
    image: bitnami/kafka:3.6.2
    container_name: kratos_kafka
    restart: always
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_RESOURCE
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 4096
        hard: 4096
    environment:
      - TZ=Asia/Shanghai
      # 降低内存使用
      - KAFKA_HEAP_OPTS=-Xmx512m -Xms256m
      # KRaft 模式配置
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kratos_kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=fMCL8kv1SWm87L_Md-I2hg
      - KAFKA_CFG_METADATA_LOG_DIR=/bitnami/kafka/kraft-combined-logs
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # 监听器配置
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://codekafka:9092,EXTERNAL://codekafka:9094
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      # 其他配置
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_LOG_RETENTION_HOURS=168
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_CFG_MIN_INSYNC_REPLICAS=1
      - KAFKA_CFG_AUTO_LEADER_REBALANCE_ENABLE=true
      - KAFKA_LOG4J_LOGGERS=kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
      - KAFKA_LOG4J_ROOT_LOGLEVEL=WARN
      - KAFKA_CFG_NUM_NETWORK_THREADS=3
      - KAFKA_CFG_NUM_IO_THREADS=8
      - KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES=102400
      - KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES=102400
      - KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES=104857600
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - kafkadata:/bitnami/kafka

  codekafka-manager:
    image: registry.cn-hangzhou.aliyuncs.com/shihao-images/kafka-manager:1.3.1.8
    restart: always
    container_name: codekafka-manager
    environment:
      ZK_HOSTS: zookeeper_sasl:2181
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: admin
      KAFKA_MANAGER_PASSWORD: Eisoo.com123
    ports:
      - 9999:9000
    volumes:
      - ./conf/application.conf:/kafka-manager-1.3.1.8/conf/application.conf
    command: -Dpidfile.path=/dev/null